### ISSUE TITLE
Public Test Server

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/chronicle#13]
https://chronicle-public-test.paragonie.com/

Post your public keys here, and I'll give you write access.

* API: https://chronicle-public-test.paragonie.com/chronicle
* Last hash: https://chronicle-public-test.paragonie.com/chronicle/lasthash
* Full export: https://chronicle-public-test.paragonie.com/chronicle/export

**Comment by paragonie-scott** [comment]
Here's a test script you can use to write arbitrary data to this Chronicle, once you have client access granted:

https://gist.github.com/paragonie-scott/d37475b0bfc9bb437f0786188f2e9e2c

Just write whatever you want to `message.txt` and run that script.

**Comment by lookyman** [comment]
`Ziysi2Ryo1jsDFBDYcHJKXzCxIlzlnPl9qTYtKpw0Ng=`

Thanks!

**Comment by paragonie-scott** [comment]
@lookyman 
```json
{
    "client-id": "tQBxwQ5ptkk4t2ZtnMfSJ6YgB393VSMl",
    "public-key": "Ziysi2Ryo1jsDFBDYcHJKXzCxIlzlnPl9qTYtKpw0Ng="
}
```
