### ISSUE TITLE
Uncaught ParagonIE\EasyDB\Exception\ConstructorFailed: Could not create a PDO connection

### ISSUE THREAD

**Issue by udf2457** [paragonie/chronicle#22]
Sorry, but am I missing something stupid here ?

> Fatal error: Uncaught ParagonIE\EasyDB\Exception\ConstructorFailed: Could not create a PDO connection. Please check your username and password. in /blah/chronicle/vendor/paragonie/easydb/src/Factory.php:65

local/settings.json is as per your example:
```
    "database": {
        "dsn": "pgsql:host=myhost;port=5432;dbname=mydb",
        "username": "myuser",
        "password": "mypass"
    }
```
and....

`psql -U myuser -d mydb -h myhost -W`

works just fine (i.e. pg_hba is correctly setup and reloaded, I can manipulate stuff as the user etc. ), and....

No errors are recorded in the postgres logs.

and .....

I know postgres connections work just fine from this machine because I've got other PHP stuff on there accessing the same postgres server.  So there's no firewalls or other stuff going on.

This is postgres 9.6.8 and php 7.2.4.

**Comment by paragonie-scott** [comment]
It's suppressing the generated PDO error message because passwords leak that way.

For debugging, remove [the try-catch around the PDO constructor](https://github.com/paragonie/easydb/blob/6813fd234bd5bd8f58ddbbe6fd161ed96af26b4f/src/Factory.php#L61-L68) and you may get more insight.

**Comment by udf2457** [comment]
Well its not doing a good job of stopping password leaks either... the password shows up right there in plain text when it spits out the error... :)

Will try your debug.

**Comment by udf2457** [comment]
Removing the try-catch yields exactly the same (I've changed the password, but left the original in so you can see the leak too ! ) ....

With try-catch:

> Fatal error: Uncaught ParagonIE\EasyDB\Exception\ConstructorFailed: Could not create a PDO connection. Please check your username and password. in /blah/chronicle/vendor/paragonie/easydb/src/Factory.php:65
> Stack trace:
> #0 /blah/chronicle/bin/make-tables.php(52): ParagonIE\EasyDB\Factory::create('pgsql:host=dx.w...', 'paragoniechroni...', 'Chr0nicleX', Array)
> #1 {main}
>   thrown in /blah/chronicle/vendor/paragonie/easydb/src/Factory.php on line 65

Without try-catch:

> Fatal error: Uncaught PDOException: could not find driver in /blah/chronicle/vendor/paragonie/easydb/src/Factory.php:62
> Stack trace:
> #0 /blah/chronicle/vendor/paragonie/easydb/src/Factory.php(62): PDO->__construct('pgsql:host=dx.w...', 'paragoniechroni...', 'Chr0nicleX', Array)
> #1 /blah/chronicle/bin/make-tables.php(52): ParagonIE\EasyDB\Factory::create('pgsql:host=dx.w...', 'paragoniechroni...', 'Chr0nicleX', Array)
> #2 {main}
>   thrown in /blah/chronicle/vendor/paragonie/easydb/src/Factory.php on line 62

**Comment by paragonie-scott** [comment]
> Fatal error: Uncaught PDOException: could not find driver

Is the pdo_pgsql extension installed?

**Comment by udf2457** [comment]
(oops, I see .... it can't find driver)

**Comment by udf2457** [comment]
ah, PHP was compiled `--with-pgsql` but not `--with-pdo-pgsql`

**Comment by paragonie-scott** [comment]
EasyDB should now give a different exception message if it's a missing driver issue (hopefully making this easier to diagnose going forward).

Did adding `--with-pdo-pgsql` fix your problem?

**Comment by udf2457** [comment]
Yeah, that did it.  Thanks.

**Comment by paragonie-scott** [comment]
Great, thank you! :)
