### ISSUE TITLE
ISSUE: Genesis Record is missing!

### ISSUE THREAD

**Issue by vzool** [paragonie/chronicle#25]
Hi,

After I got some time testing out #24, I noticed that there is no any **Genesis Record** in chain!

<img width="895" alt="screen shot 2018-07-07 at 8 14 04 am" src="https://user-images.githubusercontent.com/4952736/42407097-0a5942d0-81be-11e8-9331-5a955b4661c7.png">

Why it doesn't has one?

Thanks

**Comment by soatok** [comment]
The first block has no previous block to point to. Are you expecting NULL or the key to be undefined ?

**Comment by paragonie-scott** [comment]
I could probably change the API to store/return NULL for the prevhash.

**Comment by vzool** [comment]
@soatok I expected it point to itself before any constraints applied like "**Foreign Key**" or "**Unique**".

**Comment by paragonie-scott** [comment]
If it points to itself, that might cause issues.

We didn't specify foreign keys in our SQL schema, although it might be beneficial to do so. In either case, assuming the underlying DB supports it, a `prevhash` of `NULL` shouldn't break a foreign key relationship.

**Comment by vzool** [comment]
@paragonie-scott I don't think so, check this **tested** example on MySQL:

```SQL
-- Clean old test if exists

DROP TABLE IF EXISTS person;

-- Create table

CREATE TABLE person(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(32),
  mother_id INTEGER,
  father_id INTEGER
);

-- Genesis record

INSERT INTO person VALUES(1, '__Flat_Earth__', 1, 1);

-- Apply Constraints

ALTER TABLE person ADD CONSTRAINT person_mother_id_fk FOREIGN KEY (mother_id) REFERENCES person(id);

ALTER TABLE person ADD CONSTRAINT person_father_id_fk FOREIGN KEY (father_id) REFERENCES person(id);

-- Some custom rules like there is no human have multiple father & mother

ALTER TABLE person ADD CONSTRAINT person_id_mother_id_father_id_uk UNIQUE KEY(id, mother_id, father_id);

-- First add mother/father

INSERT INTO person VALUES(2, 'Eve', 1, 1);
INSERT INTO person VALUES(3, 'Adam', 1, 1);

--  Then add the chain for their sons/dauther

INSERT INTO person VALUES(4, 'Cain', 2, 3);
INSERT INTO person VALUES(5, 'Abel', 2, 3);
INSERT INTO person VALUES(6, 'Awan', 2, 3);

-- ... and so on.

SELECT *FROM person;

-- The Result

+----+----------------+-----------+-----------+
| id | name           | mother_id | father_id |
+----+----------------+-----------+-----------+
|  1 | __Flat_Earth__ |         1 |         1 |
|  2 | Eve            |         1 |         1 |
|  3 | Adam           |         1 |         1 |
|  4 | Cain           |         2 |         3 |
|  5 | Abel           |         2 |         3 |
|  6 | Awan           |         2 |         3 |
+----+----------------+-----------+-----------+
6 rows in set (0.00 sec)

```

**Comment by paragonie-scott** [comment]
Chronicle is basically a linked-list. You shouldn't have more than one previous node. You shouldn't have more than one next node.

The issues I'm referring to are in `while (!empty($parent))` loops, not the SQL standard.

**Comment by vzool** [comment]
Yes of course I know that, this is just for the demonstration as complete example.
The database design for fields to reference itself is very possible.
But, in our case one reference is required and good enough for the current objective.

**Comment by vzool** [comment]
My point is to enforce any rules at a database level in order to maintain a high plane of integrity, I think this way we will make something more powerful than normal blockchain, dump data to a binary files then verify later. Because, the legacy of blockchain doesn't have this level of assurance which its data could be changed at a storage level and make verify at software level after that update the bad blocks.

Now with these constraints we have both of the best worlds verification at storage and software level, so we could make the database verification as an optional thing triggered at "Red Alert" situations. So, some constraints like:

- FOREIGN KEY for (prevhash) REFERENCES chronicle_chain(currhash).
- UNIQUE on (prevhash, currhash, hashstate, summaryhash) if all of these should be unique together, or a combination of multiple fields which could make multiple group of constraints.

I think self reference tables will work perfectly if records came in order, and this is another advantage to guarantee to follow **linked list algorithm in RDBMS**.

**Comment by vzool** [comment]
@paragonie-scott Sorry, I didn't notice this `while (!empty($parent))` in your comment.
I focused to explain my idea, Ha ha ha :P
I think this `while (!empty($parent))` will become `while($parent->prevhash != $parent->currhash)`

**Comment by paragonie-scott** [comment]
I'm already updating the code to allow NULL prevhash records instead of empty string.

Foreign keys don't puke on NULLs.

**Comment by paragonie-scott** [comment]
![chronicle-test](https://user-images.githubusercontent.com/11591518/47183404-f2600680-d2f5-11e8-97a7-73067a29ac1a.png)

**Comment by vzool** [comment]
Still no any comments for what every field should do.
I'm so excited and I can help in development, I started before and stopped in database structure.
There are many fields I don't know what their roles. :(

**Comment by paragonie-scott** [comment]
> My point is to enforce any rules at a database level in order to maintain a high plane of integrity, I think this way we will make something more powerful than normal blockchain, dump data to a binary files then verify later. Because, the legacy of blockchain doesn't have this level of assurance which its data could be changed at a storage level and make verify at software level after that update the bad blocks.

The entire point of the cryptography used in Chronicle is to make it impossible to tamper with existing data without being caught. That's why we have replication, attestation, and cross-signing.

From that perspective, the foreign key constraints are good to add, but aren't a security layer. Anyone capable of reading/writing arbitrary data to the database is also capable of dropping constraints.

> UNIQUE on (prevhash, currhash, hashstate, summaryhash) if all of these should be unique together, or a combination of multiple fields which could make multiple group of constraints.

Actually, `UNIQUE(prevhash)` is enough in addition to the FOREIGN KEY to codify our requirements into the table definition. Every prevhash in chronicle_chain should point to one (and only one) currhash, ever. No exceptions.

(For the replication table, the UNIQUE constraint is over the (source, prevhash) pair.)

**Comment by paragonie-scott** [comment]
> Still no any comments for what every field should do.
> I'm so excited and I can help in development, I started before and stopped in database structure.
> There are many fields I don't know what their roles. :(

What are you trying to understand?

**Comment by vzool** [comment]
> > Still no any comments for what every field should do.
> > I'm so excited and I can help in development, I started before and stopped in database structure.
> > There are many fields I don't know what their roles. :(
> 
> What are you trying to understand?

I meant, we need some documentation for the database design and its fields.
For example, I don't know what `hashstate` is doing?

**Comment by paragonie-scott** [comment]
> I meant, we need some documentation for the database design and its fields.

I can put "write internal documentation" on a future milestone for myself, but it's not strictly necessary for most users (who will never touch Chronicle's internals; instead, they'll drop it on a VPS and then just communicate with it over HTTPS).
