### ISSUE TITLE
[Use Case] Multiple Chains - Company Agreements

### ISSUE THREAD

**Issue by vzool** [paragonie/chronicle#27]
Hi,

I have an idea to use chronicle in which is any company has many agreements with their customers, agreements like (TOS, privacy & many more).
The company is a very transparent company with their customers and it does want every customer to agree on every change for their business model.
After some time design some considerations I come up with this structure:
```php
$block = [
    [
        'type' => 'tos',
        'hash' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'terms' => ' ... ',
        'effective_at' => '2019-06-09 00:00:00',
        'functions' => [
            'deprecated' => [
                // ..
            ],
            'current' => [
                // ..
            ],
            'new' => [
                // ..
            ],
        ],
    ],
    [
        'type' => 'privacy',
        'hash' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'terms' => ' ... ',
        'effective_at' => '2018-06-09 00:00:00',
        'functions' => [
            'deprecated' => [
                // ..
            ],
            'current' => [
                // ..
            ],
            'new' => [
                // ..
            ],
        ],
    ],

    // ...
];
```
But, If just I want to update the privacy terms I will need to duplicate TOS and many others with it in order to be keep tracking last version for all agreements at `/chronicle/lasthash` , I feel current `chronicle` does not provide **multiple chains, subjects or networks**
So, I think it will be a better if add the support for multiple networks, something like this `/chronicle/{network}/lasthash`.
I prefer **subject** term over the **network**, because the url will be more fluent:

- `/chronicle/tos/lasthash`
- `/chronicle/privacy/lasthash`

The update to APIs will be:

```php
[
	{
		uri: "/chronicle/{subject}/lasthash",
		description: "Get information about the latest entry in this Chronicle at custom subject"
	},
	{
		uri: "/chronicle/lasthash",
		description: "Get information about the latest entry in this Chronicle at main subject"
	},
	{
		uri: "/chronicle/lookup/{subject}/{hash}",
		description: "Lookup the information for the given hash at custom subject"
	},
	{
		uri: "/chronicle/lookup/{hash}",
		description: "Lookup the information for the given hash at main subject"
	},
	{
		uri: "/chronicle/since/{hash}",
		description: "List all new entries since a given hash at custom subject"
	},
	{
		uri: "/chronicle/since/{subject}/{hash}",
		description: "List all new entries since a given hash at main subject"
	},
	{
		uri: "/chronicle/{subject}/export",
		description: "Export the entire Chronicle at custom subject"
	},
	{
		uri: "/chronicle/export",
		description: "Export the entire Chronicle at main subject"
	},
	{
		uri: "/chronicle/replica",
		description: "List of Chronicles being replicated onto this one (and other options)"
	},
	{
		uri: "/chronicle",
		description: "API method description"
	}
]
```
If `chronicle` will offer something like this, then it can be used in many other cases like:
- News agency `/chronicle/new-york/lasthash` as a news feed.
- Applications development Changelog `/chronicle/changelog/lasthash`.
- Blog storage.

Any suggestions are very welcome. <3

**Comment by vzool** [comment]
Some demonstration for the idea:
```
	 ------------------------------- [news-chain]
	/
[Genesis Block] ------------------------ [tos-chain]
	\
	 ------------------------------- [privacy-chain]
```

I think we need a **Genesis Block** #25 or any chain when its `prevhash` is `null` is a genesis block in its chain like this:

```
	 ------------------------------- [news-chain]
	/
[Null Reference]  ---------------------- [tos-chain]
	\
	 ------------------------------- [privacy-chain]
```
So, `Null` will be our genesis. **From Nothing Came Everything** ^_^

**Comment by paragonie-scott** [comment]
Have you looked at [HERD](https://github.com/paragonie/herd)?

You can use Chronicle as a simple ledger and build your own abstractions (i.e. channels) atop it.
You can use multiple Chronicles to solve the problem differently.

As far as the proposed change goes, I'm not sure if we want to make Chronicle support the use-case given here, but it might be worth doing in a separate project.

**Comment by vzool** [comment]
Aha, never heard of it.

For the proposed use-case in one server with every instance of Chronicle is a channel, then  I can make this as follow:

- https://www.example.com/news/chronicle
- https://www.example.com/tos/chronicle
- https://www.example.com/privacy/chronicle

Or in sub-domains fashion:

- https://news.example.com/chronicle
- https://tos.example.com/chronicle
- https://privacy.example.com/chronicle

So, every instance is a **Self Contained** and took less than 15 MB in storage, this is not a bad idea at all ^_^

**Comment by vzool** [comment]
Finally, I done setup my first online Chronicle at https://vzool.net/tos. :)
But, why not all API documented at https://vzool.net/tos/public/chronicle APIs like `/chronicle/publish`, `/chronicle/register` & `/chronicle/revoke`? :(
I'm aware of them because I browsed the source code ^_^
