### ISSUE TITLE
Unable to retrieve entry containing binary data

### ISSUE THREAD

**Issue by beeare** [paragonie/chronicle#28]
Hi,

I added a new encrypted entry to the chain (data encrypted with Sapient\SealingPublicKey). When I try to retrieve the entry for that hash using the lookup api route or export the whole chain, I receive the following error response:

{ "version": "1.0.x", "datetime": "2018-10-19T15:36:07+02:00", "status": "ERROR", "message": "Cannot JSON-encode this message." }

I checked the data stored in the chronicle_chain table for that hash and I found out that it is stored in binary form:

![grafik](https://user-images.githubusercontent.com/10948043/47221697-66151880-d3b5-11e8-8ed2-6b3adfd99314.png)

I think the data should either be stored in an encoded form or appropriate encoding should applied to ensure retrieval via REST API is possible.

Best regards,
Ben

**Comment by vzool** [comment]
I think you should encode it before send by `Base64UrlSafe::encode()`.

**Comment by paragonie-scott** [comment]
We shouldn't allow arbitrary binary data to be sent if it cannot be safely JSON decoded, unless we base64url-encode it.

**Comment by paragonie-scott** [comment]
I added a test case [here](https://github.com/paragonie/chronicle/commit/05371aa156b4a971060c5359f80adaf2a6acca7b) and could not reproduce the problem.

![sealed](https://user-images.githubusercontent.com/11591518/47240647-0586db00-d3b7-11e8-93d5-db966a8e5564.png)

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/chronicle/commit/5974eead24f7a9bcf3a8fcc75cda2e824aa16114 in the next release, Chronicle will refuse to publish any messages that will, in the future, break the JSON API when trying to return data.
