### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by geggleto** [paragonie/chronicle#3]
Do not pass around $app
- https://github.com/paragonie/chronicle/blob/master/src/Chronicle/Handlers/Lookup.php#L28
It's also never used in this class

- https://github.com/paragonie/chronicle/blob/master/src/Chronicle/Handlers/Lookup.php#L191-L207
Resource based limitation.. I think this is a problem in the EasyDB package. The results of this sql query are buffered into RAM. So if there are 128MB of items, PHP will consume 128MB... There's a chance that the process will run OOM.

Your route defintions are not ideal.
```php
$app->group('/chronicle', function () use ($app) {
    $app->post('/publish', new Register($app))
        ->add(new CheckAdminSignature());
    $app->post('/publish', new Revoke($app))
        ->add(new CheckAdminSignature());
    $app->post('/publish', new Publish($app))
        ->add(new CheckClientSignature());
    $app->get('/lasthash', new Lookup($app, 'lasthash'));
    $app->get('/lookup/[{hash}]', new Lookup($app, 'hash'));
    $app->get('/since/[{hash}]', new Lookup($app, 'since'));
    $app->get('/export', new Lookup($app, 'export'));
});
```
1) When inside the group the router is bound to the anom function allowing you to use `$this` instead of currying `$app`

2) you can use an empty route group to apply middleware to multiple things

3) With your current routes every request you are creating each of those Handlers when you do not need to. You may register handlers via a String in the container and then use the container key in the 2nd argument of the http method.

4) Furthermore, 3 applies to middleware as well.

```php
//Routes
$app->group('/chronicle', function () {
    $this->group('', function () {
        $this->post('/publish', Register::class);    //This is a bug <---
        $this->post('/publish', Revoke::class;      //This is a bug <---
        $this->post('/publish', Publish::class); 
    })->add(CheckAdminSignature::class);

    $this->get('/lasthash', 'lookup.lasthash');
    $this->get('/lookup/[{hash}]', 'lookup.hash');
    $this->get('/since/[{hash}]', 'lookup.since');
    $this->get('/export', 'lookup.export');
});

//Container Definitions
$container[CheckAdminSignature::class] = function ($c) { ... };
$container[Register::class] = function ($c) { ... };
$container[Revoke::class] = function ($c) { ... };
$container[Publish::class] = function ($c) { ... };
$container['lookup.lasthash'] = function ($c) { ... };
$container['lookup.hash'] = function ($c) { ... };
$container['lookup.since'] = function ($c) { ... };
$container['lookup.export'] = function ($c) { ... };
```

**Comment by paragonie-scott** [comment]
Is there any particular reason we shouldn't?

I'm okay with not doing that. I just thought it would be good to have it in case I needed it down the road, but ended up using my own code for my own purposes.

**Comment by geggleto** [comment]
The App class is big, it also allows you to do bad things like Service location, instead of following dependency injection. The app class is also very hard to mock.

**Comment by paragonie-scott** [comment]
Thanks for the review. The issues identified have been resolved. 👍
