### ISSUE TITLE
FK constraints and insertion of the first record

### ISSUE THREAD

**Issue by he-security** [paragonie/chronicle#39]
This commit introduced FK constraints:

080f251beeb64151af10a2643c91f57f6f7f2174

However, when the first record is inserted the value of `prevhash` is `NULL` whereas `currhash` is an actual Blakechain hash. Given the introduced constraints the insertion of the first record will fail (tested on Postgres) thus preventing chain initialisation entirely.

**Comment by paragonie-scott** [comment]
> Given  the introduced constraints the insertion of the first record will fail  (tested on Postgres) thus preventing chain initialisation entirely.

I have an instance running on SQLite and another running on PostgreSQL and neither are failing as of `v1.1.2`. Are you still encountering issues?

If you are, does this fix it?

```sql
ALTER TABLE chronicle_chain ALTER COLUMN prevhash DROP NOT NULL;
```
