### ISSUE TITLE
Invalid identifier: Invalid characters supplied.

### ISSUE THREAD

**Issue by stayallive** [paragonie/chronicle#40]
When running:

```sh
php bin/scheduled-tasks.php
```

Sometimes this is generated:

```
PHP Fatal error:  Uncaught ParagonIE\EasyDB\Exception\InvalidIdentifier: Invalid identifier: Invalid characters supplied. in /var/www/vhosts/domain.com/vendor/paragonie/easydb/src/EasyDB.php:295
Stack trace:
#0 /var/www/vhosts/domain.com/vendor/paragonie/easydb/src/EasyDB.php(745): ParagonIE\EasyDB\EasyDB->escapeIdentifier('"chronicle_chai...')
#1 /var/www/vhosts/domain.com/vendor/paragonie/easydb/src/EasyDB.php(512): ParagonIE\EasyDB\EasyDB->buildInsertQueryBoolSafe('"chronicle_chai...', Array)
#2 /var/www/vhosts/domain.com/src/Chronicle/Chronicle.php(153): ParagonIE\EasyDB\EasyDB->insert('"chronicle_chai...', Array)
#3 /var/www/vhosts/domain.com/src/Chronicle/Process/Attest.php(153): ParagonIE\Chronicle\Chronicle::extendBlakechain('{\n    "version"...', 'IryGC1_n2byTv9W...', Object(ParagonIE\Sapient\CryptographyKeys\SigningPublicKey))
#4 /var/www/vhosts/domain.com/src/Chronicle in /var/www/vhosts/domain.com/vendor/paragonie/easydb/src/EasyDB.php on line 295
```

I have no clue why... I'm running an empty Chronicle with the default `sqlite` db and a single replica (`https://php-chronicle.pie-hosted.com/chronicle`).

The replica seems to be running fine but this error puzzles me and makes me think something is not going ok... any clue?

**Comment by paragonie-scott** [comment]
This was a result of the changes made in v1.1.0, which caused double-escaping of table names. I'll get a fix out ASAP.

**Comment by paragonie-scott** [comment]
Actually, it looks like this was fixed. Please run this command on both instances and tell me if the problem disappears.

```
git tag -v v1.1.2 && git checkout v1.1.2
```

Alternatively, `git pull` will fetch the latest version if you're in the master branch.

**Comment by stayallive** [comment]
Okay, thanks. I'm not sure how much that command is scheduled but I haven't seen the error anymore 👍
