### ISSUE TITLE
[Feature Request] API for available instances

### ISSUE THREAD

**Issue by vzool** [paragonie/chronicle#43]
Hi, I'm looking forward to an API that lists all **public instances** in the chronicle app, then this will lead us to hide other instances for some use cases. By that in mind I suggest to update `local/settings.json` to support this feature like the following:

```php
{
  ...

  "instances": {
    "": {
      "name": "",
      "public": true,
      "desc": "Default public instance"
    }
  },

  ...
}
```

I mean by **public** if set to `false` is just to hide the instance in the suggested API result. Thanks

**Comment by paragonie-scott** [comment]
Making some replication instances publicly discoverable from an API makes sense to me. (The ability to run secret replicas is helpful for some threat models, but having some public instances don't hurt anything.)

**Comment by vzool** [comment]
Indeed, this will stage an important role for "**Chronicle Explorers**". ^_^

**Comment by paragonie-security** [comment]
This will be done in the next release.
